version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:management
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 30s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq:rw

  workers:
    build: .
    environment:
      - USER=rabbitmq
      - PASS=rabbitmq
      - HOST=rabbitmq
      - PORT=5672
      - LOGLEVEL=10
      - DEFINITIONS=config.toml
    depends_on:
      - rabbitmq
    volumes:
      - ./config.toml:/root/config.toml:ro

volumes:
  rabbitmq_data: null
